[google]
client_id = "637477934280-ubrq5qemh0nlf22004mr5qipl837erkv.apps.googleusercontent.com"
client_secret = "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"

[pushover]
user = "u4bs3eqg8gqsv8npdxrcqp8iezf4ad"
token = "apccb8tmg8j9pupcirg1acfkg3pzaj"
