[google_service_account]
type = "service_account"
project_id = "btc-ai-model-storage"
private_key_id = "f6baf325b30de88df55fda7cdfa4f2845461f574"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4I5H4b4ndXFEB
jrEQ+6AXqmjsrO3qIax3pIyA8g8AkavRmjmNIrmdPHHOX3Aonx8Uk09T1wkQvEYgA
QkLRe+qoteeX7Iw/sekc8TAdJJrfgHKPjeRGYxx+/8/xaT48aSGlDpn1nnGZMwPO
VlMew8Q24HZLeAoGBH8bxg0XAWZdU4PmNI4uw27muiXqGdmmYV318RqWUQrNQJzLf
qUMqeW5k8uKZVzXgrcDJL6ccZ5SYcWDVC6Tdyq1IC86YRQGup2VcrMjU+5+cyHPWc
FSalpLc/y1DTF1NqV5miJjV4PFvo7FWv7IdHdQfr4wVwyzl2nldKhCT3Sneh2mOrj
iBR7AgMBAAECggEAGLlR7qEPSkUMbWCa3rRibPsJBoo7kZ2+2fuij+ewYvusLcL+6
jfY40dL4pFG7nVbB3i2BIRRZ8lXwxFQhQ55XRhrSg0AUHrNFIQkzVB5nmw3Uk/jRx
y+kklrHsVrXq+XTyiU5P9Tr3M2QO8K0e2N+s32U9JIkCmXNKU4A0O9zrpKbMxOALm
N3FSiOe3uOwQEnLP2zEi3UeREWlhhJbFVs2eUq+VlPMeJ3y3fO3NssDzVTiEvsNsW
FSkTg8PxmbZwyBdAXoXEJJTTkYC8DbQoQMCWdM7yLwWlmE6uVaz7LRECMZGKGK6PK
mP/j/R89rawGPjSabxzHOXGTmcyNP/fUQKBgQDqYH5uzW70x5ivggO+K/euWDOFWq
7Qb0mDuj9ymq2LBZGQjd+2KH7bewACBys2geyxYQNlCVKIpEXUIGct6vBEdJOz8AD
LPQY6VGrxRTHErTnF+URcYcehfMqNwixgMOf5dUMERVhqKMqpDeo9zrpc/nJjuqlA
yt2/x5I0LsX1KwKBgQDJII6xEPpNHpX3yNHaCIrH32cqnc/KE+D01b2+Pqix5JI6w
8eQEX5F+kl9FdGIknCd0kqkbYmBX62B3UyqZTk9Ea906OjHn6UtRE/+I1nctRAfK/
tuB4NdUdTOcp+AWL7FWVQ2GdEl7Zlfy70n7WtyHfZBfBbapbZC8vjKKc9V8QKBgFV
kzuwEAXdB+cmIb2CsmFN3Y14lCih7Q6exBkj1PmG2p7CpYGb4HjBNglU6023KrLh8
BkabvOx4HdEJ9U3vmZb3epFG0qM6GrjJ5ST+9wEXtEMDbPrTzW5zD0HTC2QIrZxgM
witU2dqcVxi64OVfKVBN+BKNDydLWogho5otEt9AoGANgmRTPGKzn2RPWmvOC1jXC
Ahz8lmspx0rFNhD2Q2XtVSlIdVbtfEXXjJldnu2gq+Ryjg9RyY/TF/pIyYtI9NuaK
uyXJqWHgEIQ1hkJ5e3nWnRzjB7OYH3WLHElCpmgo99zfw8DgvgUk9FAfhYoDfhWGX
cDCu00ACoCo3vdlN44ECgYAZsx5pUeSys4NnsH2wqtN5NR2uz/SRe2JiyVGsPerDI
TUF+rP13PaTCvrXj/561xajaCpuYD49MiGEW4VBjXmNQi+YPIMo5vd4iofLMPJctv
NBUnkaHakvlm7oWcCu87cd5OziQzfjeJw8+EtH+SI81gdpmg3ImtzDWULNjy5NhA==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-drive@btc-ai-model-storage.iam.gserviceaccount.com"
client_id = "113081440117848797189"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-drive%40btc-ai-model-storage.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[pushover]
user = "u4bs3eqg8gqsv8npdxrcqp8iezf4ad"
token = "apccb8tmg8j9pupcirg1acfkg3pzaj"
